<section class="page-head"><div class="container"><a class="back-link" href="/certifications">← Catalogue</a><div class="cert-header"><div><div class="eyebrow"><?= e($cert['vendor']) ?> · <?= e(domain_label($cert['domain'])) ?></div><h1><?= e($cert['name']) ?></h1><p><?= e($cert['summary']) ?></p><div class="cert-inline-meta"><span class="difficulty <?= e(difficulty_class($cert['difficulty'] ?? 'intermediaire')) ?>"><i></i><?= e(difficulty_label($cert['difficulty'] ?? 'intermediaire')) ?></span><span class="price-pill">Prix indicatif · <?= e(format_price((int)($cert['price_eur'] ?? 0))) ?></span></div></div></div></div></section>
<section class="section"><div class="container detail-grid">
<div class="detail-main">
<div class="panel"><div class="panel-head"><div><h2>À retenir</h2><p>Les informations essentielles avant de se lancer.</p></div><span class="chip domain-<?= e($cert['domain']) ?>"><?= e(domain_label($cert['domain'])) ?></span></div><div class="key-grid"><div><span>Prérequis</span><b><?= e($cert['prerequisites']) ?></b></div><div><span>Prix indicatif</span><b><?= e(format_price((int)($cert['price_eur'] ?? 0))) ?></b></div><div><span>Certifiés</span><b><?= number_format($certifiedCount,0,' ',' ') ?></b></div><div><span>Difficulté</span><b><?= e(difficulty_label($cert['difficulty'] ?? 'intermediaire')) ?></b></div></div></div>
<div class="panel"><div class="panel-head"><div><h2>Évolution des certifications</h2><p>Indicateur de démonstration à alimenter avec des données réelles.</p></div></div><div class="chart-wrap"><canvas id="certChart" data-labels='<?= e(json_encode($labels)) ?>' data-values='<?= e(json_encode($trend)) ?>'></canvas></div></div>
<div class="panel" id="discussion"><div class="panel-head"><div><h2>Discussion</h2><p>Questions, retours d’expérience et avis d’experts.</p></div></div><?php if(Auth::check()): ?><form class="chat-form" method="post" action="/chat/poster"><input type="hidden" name="_csrf" value="<?= e($_SESSION['_csrf']) ?>"><input type="hidden" name="certification_id" value="<?= (int)$cert['id'] ?>"><textarea name="body" maxlength="800" required placeholder="Pose ta question…"></textarea><div><small>Les messages doivent rester professionnels et pertinents.</small><button class="btn btn-primary">Publier</button></div></form><?php else: ?><div class="empty-state"><p>Connecte-toi pour participer à la discussion.</p><a class="btn btn-dark" href="/connexion">Connexion</a></div><?php endif; ?><div class="thread"><?php foreach($messages as $m): ?><article class="message"><div class="avatar"><?= e(strtoupper(substr($m['user_name'],0,1))) ?></div><div><div class="message-meta"><b><?= e($m['user_name']) ?></b><?php if($m['role']!=='eleve'): ?><span class="chip tiny">EXPERT / SUPPORT</span><?php endif; ?><time><?= e(date('d/m/Y H:i',strtotime($m['created_at']))) ?></time></div><p><?= e($m['body']) ?></p></div></article><?php endforeach; if(!$messages): ?><div class="empty-state"><p>Aucun message pour le moment. Sois le premier à poser une question.</p></div><?php endif; ?></div></div>
</div>
<aside class="detail-side"><div class="panel sticky"><div class="eyebrow">APPRENDRE</div><h3>Ressources de l'école</h3><p>Des modules courts pour atteindre le niveau demandé.</p><?php foreach($resources as $r): ?><a class="resource" href="/formations"><span><?= e($r['level']) ?></span><div><b><?= e($r['title']) ?></b><small><?= e($r['duration']) ?> · Voir la formation</small></div><span>→</span></a><?php endforeach; ?></div><div class="panel dark-panel"><div class="eyebrow">ACTION</div><h3>Construis ton plan</h3><p>Retrouve cette certification dans ton espace pour suivre ta progression.</p><a class="btn btn-light" href="/tableau-de-bord">Mon espace</a></div></aside>
</div></section>
