CREATE DATABASE IF NOT EXISTS certihub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE certihub;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('eleve','support','admin') NOT NULL DEFAULT 'eleve',
 two_factor_enabled TINYINT(1) NOT NULL DEFAULT 0,
 two_factor_secret VARCHAR(64) NULL,
 active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS certifications (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 vendor VARCHAR(120) NOT NULL,
 name VARCHAR(180) NOT NULL,
 domain VARCHAR(60) NOT NULL,
 summary TEXT NOT NULL,
 prerequisites TEXT NOT NULL,
 featured TINYINT(1) NOT NULL DEFAULT 0,
 certified_count INT UNSIGNED NOT NULL DEFAULT 0,
 difficulty VARCHAR(30) NOT NULL DEFAULT 'intermediaire',
 price_eur INT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tracks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(180) NOT NULL,
 domain VARCHAR(60) NOT NULL,
 description TEXT NOT NULL,
 sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS track_certifications (
 track_id BIGINT UNSIGNED NOT NULL,
 certification_id BIGINT UNSIGNED NOT NULL,
 position INT NOT NULL DEFAULT 0,
 PRIMARY KEY(track_id, certification_id),
 CONSTRAINT fk_tc_track FOREIGN KEY(track_id) REFERENCES tracks(id) ON DELETE CASCADE,
 CONSTRAINT fk_tc_cert FOREIGN KEY(certification_id) REFERENCES certifications(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS trainings (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 certification_id BIGINT UNSIGNED NULL,
 title VARCHAR(180) NOT NULL,
 domain VARCHAR(60) NOT NULL,
 description TEXT NOT NULL,
 level VARCHAR(60) NOT NULL,
 duration VARCHAR(60) NOT NULL,
 CONSTRAINT fk_training_cert FOREIGN KEY(certification_id) REFERENCES certifications(id) ON DELETE SET NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS news (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 category VARCHAR(60) NOT NULL,
 title VARCHAR(220) NOT NULL,
 excerpt TEXT NOT NULL,
 published_at DATETIME NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_certifications (
 user_id BIGINT UNSIGNED NOT NULL,
 certification_id BIGINT UNSIGNED NOT NULL,
 status ENUM('a_planifier','en_cours','obtenue') NOT NULL,
 progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id, certification_id),
 CONSTRAINT fk_uc_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 CONSTRAINT fk_uc_cert FOREIGN KEY(certification_id) REFERENCES certifications(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 certification_id BIGINT UNSIGNED NOT NULL,
 user_id BIGINT UNSIGNED NOT NULL,
 body TEXT NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_msg_cert FOREIGN KEY(certification_id) REFERENCES certifications(id) ON DELETE CASCADE,
 CONSTRAINT fk_msg_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tickets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 subject VARCHAR(180) NOT NULL,
 message TEXT NOT NULL,
 status ENUM('ouvert','en_cours','resolu') NOT NULL DEFAULT 'ouvert',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL,
 CONSTRAINT fk_ticket_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
